/*
 * This file is generated by jOOQ.
 */
package simplewebapp.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.auto_id_company</code>
     */
    public static final Sequence<Long> AUTO_ID_COMPANY = new SequenceImpl<Long>("auto_id_company", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.auto_id_staff</code>
     */
    public static final Sequence<Long> AUTO_ID_STAFF = new SequenceImpl<Long>("auto_id_staff", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
