/*
 * This file is generated by jOOQ.
 */
package simplewebapp.jooq;


import javax.annotation.Generated;

import simplewebapp.jooq.tables.Companies;
import simplewebapp.jooq.tables.Staff;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Companies</code>.
     */
    public static final Companies COMPANIES = simplewebapp.jooq.tables.Companies.COMPANIES;

    /**
     * The table <code>public.Staff</code>.
     */
    public static final Staff STAFF = simplewebapp.jooq.tables.Staff.STAFF;
}
